config/routes.rb
Rails.application.routes.draw do
  root 'line_of_credits#index'
  resources :transactions, except: [:index]
  resources :draws
  resources :payments
  resources :line_of_credits do
    resources :transactions, only: [:index]
  end
end

app/models/draw.rb
class Draw < Transaction

  def self.sign
    1
  end

end

app/models/interest_accrual.rb
class InterestAccrual < Transaction

  def self.sign
    1
  end
  
end

app/models/line_of_credit.rb
class LineOfCredit < ActiveRecord::Base

  validates :credit_limit, :apr, presence: true, numericality: {greater_than_or_equal_to: 0.0}

  DAYS_IN_YEAR = 365

  has_many :transactions, -> { order "transactions.applied_at ASC" }

  TRANSACTION_TYPES = %w{draws payments interest_accruals}

  TRANSACTION_TYPES.each do |transaction_type|
    has_many transaction_type.to_sym, -> { order "transactions.applied_at ASC" }

    define_method(:"total_#{transaction_type}") do | at_time |
      at_time ||= end_date
      self.send(transaction_type)
        .where("applied_at <= :point_in_time", {point_in_time: at_time})
        .sum(:amount)
    end
  end

  def principal_balance at_time=end_date
    transactions.where("applied_at <= :point_in_time", {point_in_time: at_time}).reduce(0) {|sum, transaction| 
      sum + transaction.amount * transaction.class.sign
    }
  end

  def current_interest at_time=end_date
    return 0.0 unless draws.first
    start_time = draws.first.applied_at
    days_old = TimeDifference.between(start_time, at_time).in_days.to_i
    (0..days_old).to_a.reduce(0) do |sum, days_ago|
      sum + ((principal_balance(at_time - days_ago.days) * apr / 100 / DAYS_IN_YEAR))
    end
  end

  def thirty_day_interest
    return 0.0 unless draws.first
    start_time = draws.first.applied_at
    days_old = TimeDifference.between(start_time, end_date).in_days.to_i
    ((days_old - 29)..(days_old)).to_a.reduce(0) do |sum, days_ago|
      sum + (principal_balance(end_date - days_ago.days) * apr / 100 / DAYS_IN_YEAR)
    end
  end

  def end_date
    created_at + 30.days
  end
end

app/models/payment.rb
class Payment < Transaction

  validate :amount_can_not_take_the_balance_negative

  def self.sign
    -1
  end

  def amount_can_not_take_the_balance_negative
    if (line_of_credit.principal_balance + (amount * self.class.sign)) < 0
      errors.add(:amount, 'cannot exceed what is owed') 
    end
  end
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :line_of_credit

  validates :applied_at, presence: true
  validates :amount, numericality: {greater_than: 0}
  validate :amount_can_not_exceed_credit_limit

  def self.sign
    raise "Must define in subtype"
  end

  def amount_can_not_exceed_credit_limit
    if (line_of_credit.principal_balance + amount * self.class.sign) > line_of_credit.credit_limit
      errors.add(:amount, 'cannot exceed the credit limit') 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/line_of_credits_controller.rb
class LineOfCreditsController < ApplicationController
  before_action :set_line_of_credit, only: [:show, :edit, :update, :destroy]
  before_action :set_transactions, only: [:show]
  
  def index
    @line_of_credits = LineOfCredit.all
  end

  def show
  end

  def new
    @line_of_credit = LineOfCredit.new
  end

  def edit
  end

  def create
    @line_of_credit = LineOfCredit.new(line_of_credit_params)

    respond_to do |format|
      if @line_of_credit.save
        format.html { redirect_to @line_of_credit, notice: 'Line of credit was successfully created.' }
        format.json { render :show, status: :created, location: @line_of_credit }
      else
        format.html { render :new }
        format.json { render json: @line_of_credit.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @line_of_credit.update(line_of_credit_params)
        format.html { redirect_to @line_of_credit, notice: 'Line of credit was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_of_credit }
      else
        format.html { render :edit }
        format.json { render json: @line_of_credit.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @line_of_credit.destroy
    respond_to do |format|
      format.html { redirect_to line_of_credits_url, notice: 'Line of credit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_line_of_credit
      @line_of_credit = LineOfCredit.find(params[:id])
    end

    def set_transactions
      @thirty_day_interest = @line_of_credit.thirty_day_interest
      @principal_balance = @line_of_credit.principal_balance
      @total_payoff = @thirty_day_interest + @principal_balance
    end


    def line_of_credit_params
      params.require(:line_of_credit).permit(:apr, :credit_limit, :principal)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_line_of_credit, only: [:index]
  before_action :set_transaction, only: [:show, :destroy]

  def index
    @transactions = @line_of_credit.transactions
    respond_to do |format|
      format.js
    end
  end

  def create 
    @line_of_credit = LineOfCredit.find(transaction_params[:line_of_credit_id])    
    params["transaction"]["applied_at"] = @line_of_credit.created_at + params["transaction"]["applied_at"].to_i.days
    
    @transaction = Transaction.new(transaction_params)
    
    respond_to do |format|
      if @transaction.save
        format.js { render :js => "window.location.href='"+line_of_credit_path(@line_of_credit.id)+"'" }
      else
        logger.error @transaction.errors.messages
        format.js   { render partial: 'transactions/transaction_form_errors', status: :unprocessable_entity  }
      end
    end
  end

  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to @transaction.line_of_credit, notice: 'Transaction was successfully destroyed.' }
      format.js { head :no_content, status: :success }
    end
  end

  private
    
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    def set_line_of_credit
      @line_of_credit = LineOfCredit.find(params[:line_of_credit_id])
    end

    def transaction_params
      params.require(:transaction).permit(:line_of_credit_id, :amount, :type, :applied_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/line_of_credits_helper.rb
module LineOfCreditsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Credit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body class="<%= controller_name %> <%= action_name %>">

<%= yield %>

</body>
<footer>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</footer>
</html>

app/views/line_of_credits/_form.html.erb
<%= form_for(@line_of_credit) do |f| %>
  <% if @line_of_credit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_of_credit.errors.count, "error") %> prohibited this line_of_credit from being saved:</h2>

      <ul>
      <% @line_of_credit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :apr %><br>
    <%= f.text_field :apr %>
  </div>
  <div class="field">
    <%= f.label :credit_limit %><br>
    <%= f.text_field :credit_limit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_of_credits/edit.html.erb
<h1>Editing Line Of Credit</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_of_credit %> |
<%= link_to 'Back', line_of_credits_path %>

app/views/line_of_credits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Line Of Credits</h1>

<table>
  <thead>
    <tr>
      <th>Apr</th>
      <th>Credit limit</th>
      <th>Principal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_of_credits.each do |line_of_credit| %>
      <tr>
        <td><%= line_of_credit.apr %></td>
        <td><%= line_of_credit.credit_limit %></td>
        <td><%= line_of_credit.principal %></td>
        <td><%= link_to 'Show', line_of_credit %></td>
        <td><%= link_to 'Edit', edit_line_of_credit_path(line_of_credit) %></td>
        <td><%= link_to 'Destroy', line_of_credit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line of credit', new_line_of_credit_path %>

app/views/line_of_credits/new.html.erb
<h1>New Line Of Credit</h1>

<%= render 'form' %>

<%= link_to 'Back', line_of_credits_path %>

app/views/line_of_credits/show.html.erb
<div id="line_of_credit_id", data-id='<%="#{@line_of_credit.id}"%>'></div>
<p id="notice"><%= notice %></p>

<p>
  <strong>Apr:</strong>
  <%= number_to_percentage @line_of_credit.apr %>
</p>

<p>
  <strong>Credit Available:</strong>
  <%= "#{number_to_currency @principal_balance} of #{number_to_currency @line_of_credit.credit_limit}" %>
</p>

<p>
  <strong>Credit Line Opened:</strong>
  <%= @line_of_credit.created_at.to_date.to_s(:long) %>
</p>

<p>
  <strong>Interest at 30 days:</strong>
  <%= number_to_currency @thirty_day_interest %>
</p>

<p>
  <strong>Total Payoff at 30 days:</strong>
  <%= number_to_currency @total_payoff %>
</p>

<hr>

<%= render partial: 'transactions/transaction_form', locals: {line_of_credit: @line_of_credit} %>
<%= render partial: 'transactions/transactions_table', locals: {transactions: @transactions} %>

<%= link_to 'Back', line_of_credits_path %>

app/views/transactions/_transaction.html.erb
<tr>
  <td><%= TimeDifference.between(transaction.line_of_credit.created_at, transaction.applied_at).in_days.to_i %></td>
  <td><%= transaction.type %></td>
  <td><%= number_to_currency transaction.amount %></td>
  <td><%= number_to_currency transaction.line_of_credit.principal_balance(transaction.applied_at) %></td>
  <td><%= number_to_currency transaction.line_of_credit.current_interest(transaction.applied_at) %></td>
  <td><%= link_to 'Remove', transaction_path(transaction.id), method: :delete, class: 'delete-transaction' %></td>
</tr>

app/views/transactions/_transaction_form.html.erb
<div id="transaction_form">
  <%= form_for(:transaction, url: { controller: 'transactions', action: "create" }, remote: true) do |f| %>
    <div id="error_holder"></div>
    <%= f.hidden_field :line_of_credit_id, value: line_of_credit.id %>

    <div class="field">
      <%= f.label :type %><br>
      <%= select( :transaction, :type, options_for_select(["Draw", "Payment"]) ) %>
    </div>
    <div class="field">
      <%= f.label :amount %><br>
      <%= f.number_field :amount %>
    </div>
    <div class="field">
      <%= f.label :applied_at_day %><br>
      <%= select(:transaction, :applied_at, options_for_select(1..30)) %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/transactions/_transaction_form_errors.html.erb
<div id="error_explanation">
  <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

  <ul>
  <% @transaction.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>

app/views/transactions/_transactions_table.html.erb
<table id="transactions_table">
  <thead>
    <tr>
      <th>Day</th>
      <th>Type</th>
      <th>Amount</th>
      <th>Principal Balance</th>
      <th>Interest Accrued</th>
    </tr>
  </thead>

  <tbody>
    <%= render partial: 'transactions/transaction', collection: transactions %>
  </tbody>
</table>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Line of credit</th>
      <th>Amount</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.line_of_credit %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.type %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/index.js.erb
 $('#transactions_table').html("<%= escape_javascript(render partial: 'transactions/transactions_table', locals: {transactions: @transactions} ) %>");

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Line of credit:</strong>
  <%= @transaction.line_of_credit %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Type:</strong>
  <%= @transaction.type %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>